Repository k8-proxy/aws-jmeter-test-engine, pull requests merged in 2020-10, with the labels that each got.

#41 Distributes total users among all instances in ASG accurately
  .gitignore
  jmeter-icap-poc/cloudformation/README.md
  jmeter-icap-poc/cloudformation/config.env.sample
  jmeter-icap-poc/cloudformation/create_stack.py
Labels: ready-to-review

#42 update ami id in cloudformation template
  jmeter-icap-poc/cloudformation/GenerateLoadGenerators.json
  jmeter-icap-poc/cloudformation/create_stack.py
Labels: ready-to-review

#51 add jmeter parameters to the script
  jmeter-icap-poc/cloudformation/README.md
  jmeter-icap-poc/cloudformation/create_stack.py
  jmeter-icap-poc/cloudformation/script.sh
Labels: ready-to-review

#43 Moving ICAP check to separate thread group
  .DS_Store
  .gitignore
  jmeter-icap-poc/.DS_Store
  jmeter-icap-poc/scripts/.DS_Store
  jmeter-icap-poc/scripts/ICAP-POC_s3.jmx
  jmeter-icap-poc/scripts/test/test.jtl
Labels: ready-to-review

#59 choose instance type dynamically based on number of users per instance
  jmeter-icap-poc/cloudformation/GenerateLoadGenerators.json
  jmeter-icap-poc/cloudformation/README.md
  jmeter-icap-poc/cloudformation/create_stack.py
Labels: ready-to-review

#49 Updated start up script
  jmeter-icap-poc/cloudformation/GenerateLoadGenerators.json
  jmeter-icap-poc/instructions/AWS-Test-Engine-Test-Execution.md
  jmeter-icap-poc/scripts/ICAP-Dashboard-4-grafana.json
  jmeter-icap-poc/scripts/StartExecution.sh
Labels: changes requested

#66 add instructions on how github actions can be used to run tests
  .github/workflows/README.md
Labels: ready-to-review

#65 Added CreateDashboard and instruction for use
  jmeter-icap-poc/instructions/how-to-use-createDashboards-script.md
  jmeter-icap-poc/instructions/img/add_api_key.png
  jmeter-icap-poc/instructions/img/grafana_api_key_output.png
  jmeter-icap-poc/instructions/img/sidebar.png
  jmeter-icap-poc/scripts/CreateDashboard.py
Labels: ready-for-review

#67 add instance profile/role to ec2 instances
  .gitignore
  jmeter-icap-poc/cloudformation/GenerateLoadGenerators.json
  jmeter-icap-poc/cloudformation/config.env.sample
  jmeter-icap-poc/cloudformation/create_stack.py
Labels: ready-to-review

#78 Created Dashboard for ICAP live performance data
  jmeter-icap-poc/scripts/CreateDashboard.py
  jmeter-icap-poc/scripts/ICAP-live-performance-dashboard-wip.json
Labels: ready-to-review

#72 added prefix feature and prefix parameter
  jmeter-icap-poc/instructions/How-Jmeter-ICAP-PoC-Script-Works.md
  jmeter-icap-poc/scripts/ICAP-POC_s3.jmx
Labels: ready-to-review

#75 Update Jmv parameters based on total users
  jmeter-icap-poc/cloudformation/create_stack.py
Labels: ready-to-review

#70 Create CF script to create IAM role with secret manager access
  jmeter-icap-poc/cloudformation/aws-secret-manager_with_-iam-role.json
Labels: changes requested
